In [ ]:
print("hello Shahu!")

hello Shahu!


In [ ]:
print("Let's become an AI ENGINEER")

Let's become an AI ENGINEER


In [ ]:
np.array()

NameError: name 'np' is not defined

In [ ]:
#creating numpy //n-d arrays


In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])
arr1

In [ ]:
type(arr1)

In [ ]:
arr2 = np.array([1,2,3],[4,5,6])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
type(arr2)

NameError: name 'arr2' is not defined

In [ ]:
arr3 = np.zeros((2,3))
arr3

In [ ]:
arr4 = np.ones((3,3))
arr4

In [ ]:
arr5 = np.identity(5)
arr5

In [ ]:
arr6 = np.arange(5,16,2)
arr6

NameError: name 'np' is not defined

In [ ]:
arr7 = np.linspace(10,20,10)
arr7

In [ ]:
arr8 = arr7.copy()
arr8

In [ ]:
arr1


NameError: name 'arr1' is not defined

In [ ]:
arr1

In [ ]:
arr1

In [ ]:
import numpy as np


In [ ]:
arr1

NameError: name 'arr1' is not defined

In [ ]:
arr1

In [ ]:
arr1.shape()

In [ ]:
arr1.shape

In [ ]:
arr2.shape

In [ ]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

In [ ]:
arr9.shape

In [ ]:
arr9.ndim

In [ ]:
arr2.ndim

NameError: name 'arr2' is not defined

In [ ]:
arr2

In [ ]:
arr1

In [ ]:
arr1.ndim

In [ ]:
arr1.size

In [ ]:
arr9.size

In [ ]:
arr9.itemsize

In [ ]:
arr9

In [ ]:
arr9.itemsize

In [ ]:
arr8.itemsize

In [ ]:
arr8

In [ ]:
arr8.dtype

In [ ]:
arr9.dtype

In [ ]:
arr9.astype('float')

In [ ]:
arr9.astype('int')

In [ ]:
lista = range(100)
arr11 = np.arange(100)

In [ ]:
import sys

In [ ]:
print(sys.getsizeof(87)*len(lista))

In [ ]:
print(arr11.itemsize*arr11.size)

In [ ]:
import time

In [ ]:
x = range(10000000)
y = range(10000000,20000000)
start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)

In [ ]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)
start_time = time.time()
c = a+b

print(time.time()-start_time)

In [ ]:
arr1

In [ ]:
arr2

NameError: name 'arr2' is not defined

In [ ]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
for i in arr12:
  print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [ ]:
for i in np.nditer(arr12):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
arr1[2:4]

[3, 4]

In [ ]:
arr1[-1]

5

In [ ]:
arr12[2]

array([ 8,  9, 10, 11])

In [ ]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [ ]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [ ]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])